import createMDX from '@next/mdx';
import remarkGfm from 'remark-gfm';
import rehypeSlug from 'rehype-slug';
import rehypeAutolinkHeadings from 'rehype-autolink-headings';

/** @type {import('next').NextConfig} */
const nextConfig = {
  pageExtensions: ['js', 'jsx', 'ts', 'tsx', 'md', 'mdx'],
  images: {
    formats: ['image/avif', 'image/webp'],
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'X-Frame-Options', value: 'DENY' },
          { key: 'X-XDN-Robots-Tag', value: 'index,follow' },
        ],
      },
    ];
  },
  async redirects() {
    return [
      {
        source: '/mini-split-in-cold-climates',
        destination: '/heat-pump-in-cold-weather',
        permanent: true,
      },
      {
        source: '/best-2-zone-mini-split',
        destination: '/mini-split-sizing-calculator',
        permanent: true,
      },
      {
        source: '/best-3-zone-mini-split',
        destination: '/mini-split-sizing-calculator',
        permanent: true,
      },
      {
        source: '/best-4-zone-mini-split',
        destination: '/mini-split-sizing-calculator',
        permanent: true,
      },
      {
        source: '/best-5-zone-mini-split',
        destination: '/mini-split-sizing-calculator',
        permanent: true,
      },
      // ============ Archived product pages (2026-08-17) ============
      // 70 pages moved to content/_archived-product-pages/ because they contained
      // specific-SKU spec tables (fabrication risk after multiple 2025-2026 recalls).
      // Each old URL redirects to the most topically adjacent surviving page
      // (calculator, guide, explainer, or how-to). See _archived-product-pages/README.md
      // for rollback path. Note: /best-multi-zone-mini-splits is now archived too, so
      // the 4 zone-count redirects above resolve through this block's mini-split
      // sizing calculator target.
      { source: '/14-3-seer2-vs-16-seer', destination: '/seer2-comparison-calculator', permanent: true },
      { source: '/15-2-seer2-vs-16-seer', destination: '/seer2-comparison-calculator', permanent: true },
      { source: '/16-seer-vs-14-seer', destination: '/seer2-comparison-calculator', permanent: true },
      { source: '/16-seer-vs-20-seer', destination: '/seer2-comparison-calculator', permanent: true },
      { source: '/best-10000-btu-air-conditioners', destination: '/air-conditioner-btu-calculator', permanent: true },
      { source: '/best-12000-btu-air-conditioners', destination: '/air-conditioner-btu-calculator', permanent: true },
      { source: '/best-air-curtains', destination: '/air-changes-per-hour-calculator', permanent: true },
      { source: '/best-air-purifier-humidifier-combo', destination: '/air-purifier-guide', permanent: true },
      { source: '/best-air-purifiers', destination: '/air-purifier-sizing-guide', permanent: true },
      { source: '/best-air-purifiers-for-allergies', destination: '/air-purifier-guide', permanent: true },
      { source: '/best-air-purifiers-for-dust', destination: '/air-purifier-sizing-guide', permanent: true },
      { source: '/best-air-purifiers-for-mold', destination: '/how-to-identify-mold', permanent: true },
      { source: '/best-air-purifiers-for-smoke', destination: '/air-changes-per-hour-calculator', permanent: true },
      { source: '/best-air-scrubbers', destination: '/air-changes-per-hour-calculator', permanent: true },
      { source: '/best-baseboard-heaters', destination: '/heating-cost-calculator', permanent: true },
      { source: '/best-basement-dehumidifiers', destination: '/dehumidifier-guide', permanent: true },
      { source: '/best-bedroom-air-purifiers', destination: '/air-purifier-sizing-guide', permanent: true },
      { source: '/best-central-ac-brands', destination: '/ac-tonnage-calculator', permanent: true },
      { source: '/best-cold-climate-heat-pumps', destination: '/heat-pump-size-calculator', permanent: true },
      { source: '/best-commercial-dehumidifiers', destination: '/dehumidifier-guide', permanent: true },
      { source: '/best-dehumidifier-air-purifier-combo', destination: '/dehumidifier-guide', permanent: true },
      { source: '/best-diy-mini-splits', destination: '/mini-split-sizing-calculator', permanent: true },
      { source: '/best-dual-hose-portable-acs', destination: '/how-to-vent-portable-ac-without-window', permanent: true },
      { source: '/best-electric-fireplaces', destination: '/heating-cost-calculator', permanent: true },
      { source: '/best-electric-tankless-water-heaters', destination: '/water-heater-sizing-calculator', permanent: true },
      { source: '/best-energy-efficient-space-heaters', destination: '/heating-cost-calculator', permanent: true },
      { source: '/best-evaporative-coolers', destination: '/air-conditioner-btu-calculator', permanent: true },
      { source: '/best-garage-heaters', destination: '/heating-cost-calculator', permanent: true },
      { source: '/best-gas-furnace-brands', destination: '/furnace-guide', permanent: true },
      { source: '/best-hepa-air-purifiers', destination: '/hepa-filter-explained', permanent: true },
      { source: '/best-humidifiers-for-bedroom', destination: '/dehumidifier-guide', permanent: true },
      { source: '/best-humidifiers-for-large-rooms', destination: '/dehumidifier-guide', permanent: true },
      { source: '/best-hvac-air-filters', destination: '/merv-rating-chart', permanent: true },
      { source: '/best-hvac-brands-ranked', destination: '/furnace-guide', permanent: true },
      { source: '/best-indoor-air-quality-monitors', destination: '/how-to-improve-indoor-air-quality', permanent: true },
      { source: '/best-infrared-heaters', destination: '/heating-cost-calculator', permanent: true },
      { source: '/best-large-room-air-purifiers', destination: '/air-changes-per-hour-calculator', permanent: true },
      { source: '/best-mini-split-ac-units', destination: '/mini-split-sizing-calculator', permanent: true },
      { source: '/best-mini-split-for-garage', destination: '/mini-split-sizing-calculator', permanent: true },
      { source: '/best-mini-split-heat-pumps', destination: '/mini-split-sizing-calculator', permanent: true },
      { source: '/best-multi-zone-mini-splits', destination: '/mini-split-sizing-calculator', permanent: true },
      { source: '/best-oil-furnace', destination: '/furnace-guide', permanent: true },
      { source: '/best-pellet-stoves', destination: '/heating-cost-calculator', permanent: true },
      { source: '/best-portable-ac-for-apartment', destination: '/air-conditioner-btu-calculator', permanent: true },
      { source: '/best-portable-ac-heater-combos', destination: '/air-conditioner-btu-calculator', permanent: true },
      { source: '/best-portable-air-conditioners', destination: '/air-conditioner-btu-calculator', permanent: true },
      { source: '/best-portable-generators', destination: '/what-size-generator-for-fridge', permanent: true },
      { source: '/best-small-dehumidifiers', destination: '/dehumidifier-guide', permanent: true },
      { source: '/best-small-heaters', destination: '/heating-cost-calculator', permanent: true },
      { source: '/best-smart-thermostats', destination: '/smart-thermostat-savings', permanent: true },
      { source: '/best-space-heaters-for-large-rooms', destination: '/heating-cost-calculator', permanent: true },
      { source: '/best-tankless-gas-water-heaters', destination: '/water-heater-sizing-calculator', permanent: true },
      { source: '/best-tankless-water-heaters', destination: '/water-heater-sizing-calculator', permanent: true },
      { source: '/best-thermostat-for-heat-pump', destination: '/smart-thermostat-savings', permanent: true },
      { source: '/best-tower-fans', destination: '/kwh-cost-calculator', permanent: true },
      { source: '/best-ventless-propane-heaters', destination: '/heating-cost-calculator', permanent: true },
      { source: '/best-wall-mount-electric-fireplaces', destination: '/heating-cost-calculator', permanent: true },
      { source: '/best-water-heaters', destination: '/water-heater-sizing-calculator', permanent: true },
      { source: '/best-whole-house-dehumidifiers', destination: '/dehumidifier-guide', permanent: true },
      { source: '/best-whole-house-generators', destination: '/what-size-generator-for-fridge', permanent: true },
      { source: '/best-window-air-conditioners', destination: '/air-conditioner-btu-calculator', permanent: true },
      { source: '/daikin-mini-split-reviews', destination: '/mini-split-sizing-calculator', permanent: true },
      { source: '/dyson-vs-levoit-vs-coway', destination: '/air-purifier-guide', permanent: true },
      { source: '/electric-vs-gas-tankless', destination: '/water-heater-sizing-calculator', permanent: true },
      { source: '/generator-vs-solar-battery-backup', destination: '/home-battery-backup-guide', permanent: true },
      { source: '/heat-pump-vs-mini-split', destination: '/heat-pump-guide', permanent: true },
      { source: '/mrcool-3rd-gen-vs-4th-gen', destination: '/mini-split-sizing-calculator', permanent: true },
      { source: '/nest-vs-ecobee-vs-honeywell', destination: '/smart-thermostat-savings', permanent: true },
      { source: '/senville-mini-split-reviews', destination: '/mini-split-air-conditioners', permanent: true },
      { source: '/trane-vs-carrier', destination: '/furnace-guide', permanent: true },
      // ---- Raptive Step 1: fabricated product/brand pages archived 2026-09 ----
      { source: '/airdog-air-purifier-review', destination: '/air-purifier-guide', permanent: true },
      { source: '/alen-breathesmart-air-purifiers', destination: '/air-purifier-guide', permanent: true },
      { source: '/battery-operated-heaters', destination: '/space-heater-guide', permanent: true },
      { source: '/best-electric-furnace', destination: '/furnace-guide', permanent: true },
      { source: '/biggest-portable-acs', destination: '/portable-air-conditioners', permanent: true },
      { source: '/biggest-window-acs', destination: '/window-air-conditioners', permanent: true },
      { source: '/blueair-air-purifiers', destination: '/air-purifier-guide', permanent: true },
      { source: '/brand-reviews', destination: '/articles', permanent: true },
      { source: '/buying-guides', destination: '/articles', permanent: true },
      { source: '/casement-window-air-conditioners', destination: '/window-air-conditioners', permanent: true },
      { source: '/cassette-ceiling-air-conditioners', destination: '/mini-split-air-conditioners', permanent: true },
      { source: '/cheapest-portable-air-conditioners', destination: '/portable-air-conditioners', permanent: true },
      { source: '/coway-air-purifiers', destination: '/air-purifier-guide', permanent: true },
      { source: '/dyson-air-purifiers', destination: '/air-purifier-guide', permanent: true },
      { source: '/germguardian-air-purifiers', destination: '/air-purifier-guide', permanent: true },
      { source: '/honeywell-air-purifiers', destination: '/air-purifier-guide', permanent: true },
      { source: '/iqair-healthpro-plus-review', destination: '/air-purifier-guide', permanent: true },
      { source: '/levoit-air-purifiers', destination: '/air-purifier-guide', permanent: true },
      { source: '/lightweight-window-acs', destination: '/window-air-conditioners', permanent: true },
      { source: '/low-profile-window-acs', destination: '/window-air-conditioners', permanent: true },
      { source: '/medify-air-purifiers', destination: '/air-purifier-guide', permanent: true },
      { source: '/mini-split-brands-ranked', destination: '/mini-split-air-conditioners', permanent: true },
      { source: '/mini-split-for-bedroom', destination: '/mini-split-sizing-calculator', permanent: true },
      { source: '/mini-split-line-set-covers', destination: '/mini-split-installation-cost', permanent: true },
      { source: '/molekule-air-purifier-review', destination: '/air-purifier-guide', permanent: true },
      { source: '/most-energy-efficient-dehumidifiers', destination: '/dehumidifier-guide', permanent: true },
      { source: '/most-energy-efficient-window-acs', destination: '/window-air-conditioners', permanent: true },
      { source: '/mrcool-diy-mini-split-review', destination: '/mini-split-sizing-calculator', permanent: true },
      { source: '/outdoor-portable-tankless-heaters', destination: '/tankless-water-heater-guide', permanent: true },
      { source: '/portable-ac-window-seal-kits', destination: '/how-to-vent-portable-ac-without-window', permanent: true },
      { source: '/quietest-air-purifiers', destination: '/air-purifier-sizing-guide', permanent: true },
      { source: '/quietest-dehumidifiers', destination: '/dehumidifier-guide', permanent: true },
      { source: '/quietest-mini-splits', destination: '/hvac-noise-levels-explained', permanent: true },
      { source: '/quietest-portable-air-conditioners', destination: '/hvac-noise-levels-explained', permanent: true },
      { source: '/quietest-window-acs', destination: '/hvac-noise-levels-explained', permanent: true },
      { source: '/safest-heater-for-bedroom', destination: '/space-heater-guide', permanent: true },
      { source: '/safest-space-heaters', destination: '/space-heater-guide', permanent: true },
      { source: '/smallest-acs-for-small-rooms', destination: '/air-conditioner-btu-calculator', permanent: true },
      { source: '/smallest-air-purifiers', destination: '/air-purifier-sizing-guide', permanent: true },
      { source: '/smallest-mini-splits', destination: '/mini-split-sizing-calculator', permanent: true },
      { source: '/smallest-portable-acs', destination: '/portable-air-conditioners', permanent: true },
      { source: '/smallest-tankless-water-heaters', destination: '/what-size-tankless-water-heater', permanent: true },
      { source: '/smallest-window-acs', destination: '/window-air-conditioners', permanent: true },
      { source: '/through-the-wall-air-conditioners', destination: '/window-air-conditioners', permanent: true },
      { source: '/wall-mounted-air-purifiers', destination: '/air-purifier-placement', permanent: true },
      { source: '/window-ac-support-brackets', destination: '/how-to-tilt-window-ac', permanent: true },
      { source: '/window-ac-with-heater', destination: '/window-air-conditioners', permanent: true },
      { source: '/winix-air-purifiers', destination: '/air-purifier-guide', permanent: true },
      // consolidation wave 1 — 91 duplicate/variant pages merged into survivors (308)
      { source: '/what-is-seer-rating', destination: '/seer2-rating-explained', permanent: true },
      { source: '/good-seer-rating-for-ac', destination: '/seer2-rating-explained', permanent: true },
      { source: '/how-to-calculate-seer', destination: '/seer2-rating-explained', permanent: true },
      { source: '/hvac-efficiency-ratings-compared', destination: '/seer2-rating-explained', permanent: true },
      { source: '/seer-vs-seer2', destination: '/seer2-to-seer-conversion', permanent: true },
      { source: '/seer2-savings-calculator', destination: '/seer2-comparison-calculator', permanent: true },
      { source: '/is-higher-seer-worth-it', destination: '/seer2-comparison-calculator', permanent: true },
      { source: '/14-seer-vs-16-seer-vs-20-seer', destination: '/seer2-comparison-calculator', permanent: true },
      { source: '/eer-rating-explained', destination: '/eer-chart-for-ac-units', permanent: true },
      { source: '/eer2-rating-explained', destination: '/eer-chart-for-ac-units', permanent: true },
      { source: '/eer-vs-seer', destination: '/eer-chart-for-ac-units', permanent: true },
      { source: '/ceer-rating-explained', destination: '/eer-chart-for-ac-units', permanent: true },
      { source: '/ieer-explained', destination: '/eer-chart-for-ac-units', permanent: true },
      { source: '/eseer-explained', destination: '/eer-chart-for-ac-units', permanent: true },
      { source: '/hspf2-rating-explained', destination: '/hspf-rating-explained', permanent: true },
      { source: '/heat-pump-cop-explained', destination: '/coefficient-of-performance', permanent: true },
      { source: '/hvac-efficiency-texas', destination: '/minimum-seer-rating-by-state', permanent: true },
      { source: '/ac-size-for-1000-sq-ft', destination: '/ac-tonnage-calculator', permanent: true },
      { source: '/ac-size-for-1500-sq-ft', destination: '/ac-tonnage-calculator', permanent: true },
      { source: '/ac-size-for-2000-sq-ft', destination: '/ac-tonnage-calculator', permanent: true },
      { source: '/ac-size-for-2500-sq-ft', destination: '/ac-tonnage-calculator', permanent: true },
      { source: '/ac-size-for-3000-sq-ft', destination: '/ac-tonnage-calculator', permanent: true },
      { source: '/ac-size-for-500-sq-ft', destination: '/air-conditioner-btu-calculator', permanent: true },
      { source: '/5000-btu-air-conditioner-room-size', destination: '/air-conditioner-btu-calculator', permanent: true },
      { source: '/how-many-btu-per-square-foot', destination: '/air-conditioner-btu-calculator', permanent: true },
      { source: '/hvac-cost-california', destination: '/hvac-cost-by-state', permanent: true },
      { source: '/hvac-cost-illinois', destination: '/hvac-cost-by-state', permanent: true },
      { source: '/hvac-cost-new-york', destination: '/hvac-cost-by-state', permanent: true },
      { source: '/hvac-cost-florida', destination: '/hvac-cost-by-state', permanent: true },
      { source: '/hvac-cost-texas', destination: '/hvac-cost-by-state', permanent: true },
      { source: '/electricity-cost-by-state', destination: '/kwh-cost-calculator', permanent: true },
      { source: '/average-electric-bill-by-state', destination: '/kwh-cost-calculator', permanent: true },
      { source: '/energy-costs-guide', destination: '/kwh-cost-calculator', permanent: true },
      { source: '/time-of-use-rates-explained', destination: '/kwh-cost-calculator', permanent: true },
      { source: '/electric-water-heating-cost-by-state', destination: '/electric-water-heating-cost', permanent: true },
      { source: '/solar-panel-cost-by-state', destination: '/solar-panel-calculator', permanent: true },
      { source: '/energy-star-tax-credits', destination: '/hvac-tax-credits-2026', permanent: true },
      { source: '/seer-rating-tax-credits', destination: '/hvac-tax-credits-2026', permanent: true },
      { source: '/25c-tax-credit-explained', destination: '/hvac-tax-credits-2026', permanent: true },
      { source: '/carrier-hvac-age-serial-number', destination: '/hvac-serial-number-decoder', permanent: true },
      { source: '/goodman-ac-age-serial-number', destination: '/hvac-serial-number-decoder', permanent: true },
      { source: '/water-heater-breaker-size', destination: '/water-heater-wire-size', permanent: true },
      { source: '/water-heater-amps', destination: '/water-heater-wire-size', permanent: true },
      { source: '/water-heater-wattage', destination: '/water-heater-wire-size', permanent: true },
      { source: '/tankless-water-heater-breaker-size', destination: '/water-heater-wire-size', permanent: true },
      { source: '/tankless-water-heater-wire-size', destination: '/water-heater-wire-size', permanent: true },
      { source: '/tankless-water-heater-electricity', destination: '/water-heater-wire-size', permanent: true },
      { source: '/tankless-vs-tank-water-heater', destination: '/tankless-water-heater-guide', permanent: true },
      { source: '/water-heater-cost-to-install', destination: '/tankless-water-heater-cost', permanent: true },
      { source: '/what-wire-size-for-50-amp', destination: '/wire-for-220-volt', permanent: true },
      { source: '/what-wire-size-for-30-amp', destination: '/wire-for-220-volt', permanent: true },
      { source: '/10-2-or-10-3-wire-for-ac', destination: '/wire-for-220-volt', permanent: true },
      { source: '/portable-ac-vs-window-ac', destination: '/portable-vs-window-ac', permanent: true },
      { source: '/do-window-acs-pull-air-from-outside', destination: '/do-portable-acs-pull-air-from-outside', permanent: true },
      { source: '/how-do-portable-acs-work', destination: '/portable-air-conditioners', permanent: true },
      { source: '/can-you-use-portable-ac-without-hose', destination: '/how-to-vent-portable-ac-without-window', permanent: true },
      { source: '/window-ac-installation-guide', destination: '/how-to-tilt-window-ac', permanent: true },
      { source: '/window-ac-vs-mini-split', destination: '/mini-split-vs-central-air', permanent: true },
      { source: '/central-ac-vs-mini-split-vs-window', destination: '/mini-split-vs-central-air', permanent: true },
      { source: '/saddle-u-shaped-air-conditioners', destination: '/window-air-conditioners', permanent: true },
      { source: '/window-too-small-for-ac', destination: '/window-air-conditioners', permanent: true },
      { source: '/programmable-vs-smart-thermostat', destination: '/smart-thermostat-savings', permanent: true },
      { source: '/thermostat-heat-on-but-no-heat', destination: '/furnace-blowing-cold-air', permanent: true },
      { source: '/furnace-flame-sensor', destination: '/furnace-blowing-cold-air', permanent: true },
      { source: '/furnace-filter-merv-rating', destination: '/merv-rating-chart', permanent: true },
      { source: '/dirty-furnace-filter-photos', destination: '/how-often-change-hvac-filter', permanent: true },
      { source: '/furnace-maintenance', destination: '/hvac-maintenance-checklist', permanent: true },
      { source: '/how-long-do-furnaces-last', destination: '/hvac-system-lifespan', permanent: true },
      { source: '/do-furnaces-have-pilot-lights', destination: '/pilot-light-gas-usage', permanent: true },
      { source: '/upflow-vs-downflow-furnace', destination: '/furnace-guide', permanent: true },
      { source: '/heat-pump-vs-ac', destination: '/heat-pump-guide', permanent: true },
      { source: '/generator-cost-per-kwh', destination: '/propane-generator-usage-per-hour', permanent: true },
      { source: '/natural-gas-generator-running-cost', destination: '/propane-generator-usage-per-hour', permanent: true },
      { source: '/how-long-generator-on-5-gallons', destination: '/propane-generator-usage-per-hour', permanent: true },
      { source: '/how-long-do-generators-last', destination: '/generator-guide', permanent: true },
      { source: '/mini-split-maintenance-guide', destination: '/mini-split-air-conditioners', permanent: true },
      { source: '/dehumidifier-electricity-usage', destination: '/dehumidifier-running-cost', permanent: true },
      { source: '/how-does-a-dehumidifier-work', destination: '/dehumidifier-guide', permanent: true },
      { source: '/ac-dry-mode-vs-dehumidifier', destination: '/dry-mode-in-ac', permanent: true },
      { source: '/does-dehumidifier-cool-a-room', destination: '/dehumidifier-guide', permanent: true },
      { source: '/basement-dehumidifier-setting', destination: '/dehumidifier-guide', permanent: true },
      { source: '/dehumidifier-vs-air-purifier', destination: '/dehumidifier-guide', permanent: true },
      { source: '/indoor-air-quality-guide', destination: '/how-to-improve-indoor-air-quality', permanent: true },
      { source: '/cadr-rating-explained', destination: '/air-purifier-sizing-guide', permanent: true },
      { source: '/do-air-purifiers-really-work', destination: '/air-purifier-guide', permanent: true },
      { source: '/allergen-control-guide', destination: '/how-to-improve-indoor-air-quality', permanent: true },
      { source: '/mold-prevention-guide', destination: '/how-to-identify-mold', permanent: true },
      { source: '/mold-remediation-cost', destination: '/how-to-identify-mold', permanent: true },
      { source: '/electric-fireplace-cost-to-run', destination: '/space-heater-guide', permanent: true },
      { source: '/space-heater-vs-central-heat', destination: '/space-heater-guide', permanent: true },
      { source: '/home-energy-audit-diy', destination: '/hvac-energy-saving-tips', permanent: true },
      // ============ end archived product pages ============
    ];
  },
};

const withMDX = createMDX({
  options: {
    remarkPlugins: [remarkGfm],
    rehypePlugins: [rehypeSlug, [rehypeAutolinkHeadings, { behavior: 'wrap' }]],
  },
});

export default withMDX(nextConfig);
